# Use the official MySQL image as a base
FROM mysql:5.7

# Copy the init SQL file into the /docker-entrypoint-initdb.d directory
# This will automatically execute the SQL file when MySQL is initialized for the first time
COPY ./init_db.sql /docker-entrypoint-initdb.d/

# Expose the default MySQL port
EXPOSE 3306

# The default command is "mysqld", which will start the MySQL server.
CMD ["mysqld"]
