version: '3'
services:
  php-apache:
    build:
      context: ../  # Use the parent directory as the build context
      dockerfile: Docker/Dockerfile.apache.opt
    image: plib-php-5.6-apache  # Name the image after your project (plib)
    volumes:
      - ..:/var/www/html  # For testing
      - ../_uploads:/var/www/html/_uploads  # For faster build
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
